#!/usr/bin/env bash
# Generate a complete GitHub issue triage report
#
# Usage: triage_report.sh [--output FILE]
#
# Environment variables:
#   GITHUB_REPO     - GitHub repository (default: auto-detected)
#   DESIGN_DOCS_DIR - Root directory for design docs (default: design_docs)
#   CHANGELOG_PATH  - Path to changelog (default: CHANGELOG.md)
#   STALE_DAYS      - Days before an issue is considered stale (default: 30)

set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

OUTPUT_FILE=""
DESIGN_DOCS_DIR="${DESIGN_DOCS_DIR:-${PROJECT_ROOT}/design_docs}"
CHANGELOG_PATH="${CHANGELOG_PATH:-${PROJECT_ROOT}/CHANGELOG.md}"
STALE_DAYS="${STALE_DAYS:-30}"

if [[ -z "${GITHUB_REPO:-}" ]]; then
    GITHUB_REPO=$(git remote get-url origin 2>/dev/null | sed 's|.*github.com[:/]||' | sed 's|\.git$||' || echo "")
fi
REPO="${GITHUB_REPO}"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --output) OUTPUT_FILE="$2"; shift 2 ;;
        --stale-days) STALE_DAYS="$2"; shift 2 ;;
        *) echo "Unknown option: $1" >&2; exit 1 ;;
    esac
done

cd "$PROJECT_ROOT"

"$SCRIPT_DIR/check_auth.sh" || exit 1

echo ""
echo "Generating Triage Report..."
echo ""

ISSUES=$(gh issue list --repo "$REPO" --state open --limit 100 --json number,title,labels,createdAt,updatedAt,assignees,url,body 2>/dev/null || echo "[]")

TOTAL=$(echo "$ISSUES" | jq 'length')

if [[ "$TOTAL" == "0" ]]; then
    echo "No open issues found. Issue tracker is clean!"
    exit 0
fi

# Calculate stale date
if command -v gdate &> /dev/null; then
    STALE_DATE=$(gdate -d "$STALE_DAYS days ago" +%Y-%m-%dT%H:%M:%SZ)
elif date --version 2>/dev/null | grep -q GNU; then
    STALE_DATE=$(date -d "$STALE_DAYS days ago" +%Y-%m-%dT%H:%M:%SZ)
else
    STALE_DATE=$(date -v-${STALE_DAYS}d +%Y-%m-%dT%H:%M:%SZ)
fi

# Categorize issues
echo "$ISSUES" | jq -c '.[]' | while read -r issue; do
    NUMBER=$(echo "$issue" | jq -r '.number')
    TITLE=$(echo "$issue" | jq -r '.title')
    UPDATED=$(echo "$issue" | jq -r '.updatedAt')
    LABELS=$(echo "$issue" | jq -r '.labels | map(.name) | join(",")')
    URL=$(echo "$issue" | jq -r '.url')

    # Check if closable
    IN_IMPLEMENTED=$(grep -rl "#$NUMBER" "$DESIGN_DOCS_DIR/implemented/" 2>/dev/null | head -1 || echo "")
    IN_CHANGELOG=$(grep -l "#$NUMBER" "$CHANGELOG_PATH" 2>/dev/null | head -1 || echo "")

    if [[ -n "$IN_IMPLEMENTED" ]] || [[ -n "$IN_CHANGELOG" ]]; then
        echo "CLOSABLE|$NUMBER|$TITLE|$LABELS|$URL"
        continue
    fi

    # Check if covered
    IN_PLANNED=$(grep -rl "#$NUMBER" "$DESIGN_DOCS_DIR/planned/" 2>/dev/null | head -1 || echo "")

    if [[ -n "$IN_PLANNED" ]]; then
        echo "COVERED|$NUMBER|$TITLE|$LABELS|$IN_PLANNED"
        continue
    fi

    # Check if stale
    if [[ "$UPDATED" < "$STALE_DATE" ]]; then
        echo "STALE|$NUMBER|$TITLE|$LABELS|$UPDATED"
    else
        echo "ORPHANED|$NUMBER|$TITLE|$LABELS|$URL"
    fi
done > /tmp/triage_categories_$$

# Count categories
count_category() {
    grep -c "^$1|" /tmp/triage_categories_$$ 2>/dev/null || echo "0"
}

CLOSABLE_COUNT=$(count_category "CLOSABLE")
COVERED_COUNT=$(count_category "COVERED")
STALE_COUNT=$(count_category "STALE")
ORPHANED_COUNT=$(count_category "ORPHANED")

# Generate report
REPORT="# GitHub Issue Triage Report\n\n"
REPORT+="**Generated:** $(date '+%Y-%m-%d %H:%M:%S')\n"
REPORT+="**Repository:** $REPO\n\n"
REPORT+="## Summary\n\n"
REPORT+="| Category | Count |\n|----------|-------|\n"
REPORT+="| Total Open | $TOTAL |\n"
REPORT+="| Closable (implemented) | $CLOSABLE_COUNT |\n"
REPORT+="| Covered (has design doc) | $COVERED_COUNT |\n"
REPORT+="| Orphaned (needs attention) | $ORPHANED_COUNT |\n"
REPORT+="| Stale (${STALE_DAYS}+ days inactive) | $STALE_COUNT |\n\n"

if [[ "$CLOSABLE_COUNT" -gt 0 ]]; then
    REPORT+="## Closable Issues\n\n"
    while IFS='|' read -r cat num title labels extra; do
        [[ "$cat" != "CLOSABLE" ]] && continue
        REPORT+="- **#$num**: $title\n"
    done < /tmp/triage_categories_$$
    REPORT+="\n**Action:** Run \`scripts/find_closable.sh --close\`\n\n"
fi

if [[ "$ORPHANED_COUNT" -gt 0 ]]; then
    REPORT+="## Orphaned Issues (Need Attention)\n\n"
    while IFS='|' read -r cat num title labels url; do
        [[ "$cat" != "ORPHANED" ]] && continue
        REPORT+="- **#$num**: $title\n"
    done < /tmp/triage_categories_$$
    REPORT+="\n"
fi

if [[ "$STALE_COUNT" -gt 0 ]]; then
    REPORT+="## Stale Issues\n\n"
    while IFS='|' read -r cat num title labels updated; do
        [[ "$cat" != "STALE" ]] && continue
        REPORT+="- **#$num**: $title (last updated: ${updated%%T*})\n"
    done < /tmp/triage_categories_$$
    REPORT+="\n"
fi

REPORT+="---\n*Generated by github-issue-triage skill*\n"

rm -f /tmp/triage_categories_$$

if [[ -n "$OUTPUT_FILE" ]]; then
    echo -e "$REPORT" > "$OUTPUT_FILE"
    echo "Report written to: $OUTPUT_FILE"
else
    echo -e "$REPORT"
fi
